cmake_minimum_required(VERSION 3.30)
project(2025)

set(CMAKE_CXX_STANDARD 20)

add_executable(2025 main.cpp
        0329_29.c
        0329_29.c
        0329_29.c
        0329_30.cpp
        0329_31.cpp
        0329_32.cpp
        0329_33.cpp
        032934.cpp
        0331_1.cpp
        0401_1.cpp
        0401_2.cpp
        0401_3.cpp
        0402_1.cpp
        0402_2.cpp
        0402_3.cpp
        0403_1.cpp
        0403_2.cpp
        0403_3.cpp
        0403_4.cpp
        0403_5.cpp
        0403_6.cpp
        0403_7.cpp
        0403_10.cpp
        0404_1.cpp
        0405_1.cpp
        0405_2.cpp
        0405_3.cpp
        0405_4.cpp
        0405_5.cpp
        0405_6.cpp
        0405_7.cpp
        0405_8.cpp
        0405_9.cpp
        0405_10.cpp
        0405_11.cpp
        0408_1.cpp
        0408_2.cpp
        0408_3.cpp
        0408_4.cpp
        0408_5.cpp
        0408_6.cpp
        0409_1.cpp
        0409_2.cpp
        0409_3.cpp
        0409_4.cpp
        0409_5.cpp
        0409_6.cpp
        0409_7.cpp
        0409_8.cpp
        0409_9.cpp
        0409_10.cpp
        0409_11.cpp
        0409_12.cpp
        0409_13.cpp
        0409_14.cpp
        0409_15.cpp
        0409_16.cpp
        0409_17.cpp
        0409_18.cpp
        0409_19.cpp
        0410_1.cpp
        0410_2.cpp
        0410_3.cpp
        0410_4.cpp
        0411_1.cpp
        0411_2.cpp
        0411_3.cpp
        0411_4.cpp
        0411_5.cpp
        0411_6.cpp
        0411_7.cpp
        0412_1.cpp
        0412_2.cpp
        0412_3.cpp
        0412_4.cpp
        0412_5.cpp
        0415_1.cpp
        0415_2.cpp
        0415_3.cpp
        0415_4.cpp
        0415_5.cpp
        0415_6.cpp
        0416_1.cpp
        0416_2.cpp
        0416_3.cpp
        0416_4.cpp
        0417_1.cpp
        0417_2.cpp
        0417_3.cpp
        0417_4.cpp
        0417_5.cpp
        0417_6.cpp
        0417_7.cpp
        0417_8.cpp
        0417_9.cpp
        0418_1.cpp
        0418_2.cpp
        0418_3.cpp
        0418_4.cpp
        0418_5.cpp
        0419_1.cpp
        0419_2.cpp
        0419_3.cpp
        0419_4.cpp
        0419_5.cpp
        0419_6.cpp
        0419_7.cpp
        0419_8.cpp
        0419_9.cpp
        0419_10.cpp
        0419_11.cpp
        0419_12.cpp
        0419_13.cpp
        0419_14.cpp
        0419_15.cpp
        0419_16.cpp
        0419_17.cpp
        0420_1.cpp
        0420_2.cpp
        0420_3.cpp
        0420_4.cpp
        0420_5.cpp
        0420_6.cpp
        0420_7.cpp
        0420_8.cpp
        0420_9.cpp
        0420_10.cpp
        0420_11.cpp
        0420_12.cpp
        0420_13.cpp
        0420_14.cpp
        0421_1.cpp
        0421_15.cpp
        0421_2.cpp
        0421_3.cpp
        0421_4.cpp
        0421_5.cpp
        0422_1.cpp
        0422_2.cpp
        0422_3.cpp
        0422_4.cpp
        0422_5.cpp
        0422_6.cpp
        0422_7.cpp
        0423_1.cpp
        0423_2.cpp
        0423_3.cpp
        0423_4.cpp
        0423_5.cpp
        0423_6.cpp
        0423_7.cpp
        0423_8.cpp
        0423_9.cpp
        0423_10.cpp
        0424_1.cpp
        0424_2.cpp
        0424_3.cpp
        0424_4.cpp
        0424_5.cpp
        0424_6.cpp
        0424_7.cpp
        0424_8.cpp
        0424_9.cpp
        0424_10.cpp
        0424_11.cpp
        0425_1.cpp
        0425_2.cpp
        0425_3.cpp
        0425_4.cpp
        0425_5.cpp
        0425_6.cpp
        0425_7.cpp
        0425_8.cpp
        0425_9.cpp
        0425_10.cpp
        0425_11.cpp
        0426_1.cpp
        0426_2.cpp
        0426_3.cpp
        0426_4.cpp
        0426_5.cpp
        0428_1.cpp
        0428_2.cpp
        0428_3.cpp
        0428_4.cpp
        0428_5.cpp
        0428_6.cpp
        0428_7.cpp
        0429_1.cpp
        0429_2.cpp
        0429_3.cpp
        0429_4.cpp
        0429_5.cpp
        0429_6.cpp
        0429_7.cpp
        0429_8.cpp
        0429_9.cpp
        0429_10.cpp
        0429_11.cpp
        0429_12.cpp
        0429_13.cpp
        0429_14.cpp
        0429_15.cpp
        0429_16.cpp
        0429_17.cpp
        0429_18.cpp
        0429_19.cpp
        0429_20.cpp
        0429_21.cpp
        0429_22.cpp
        0429_23.cpp
        0429_24.cpp
        0429_25.cpp
        0429_26.cpp
        0429_27.cpp
        0429_28.cpp
        0429_29.cpp
        0429_30.cpp
        0429_31.cpp
        0429_32.cpp
        0429_33.cpp
        0429_34.cpp
        0429_35.cpp
        0429_36.cpp
        0429_37.cpp
        0429_38.cpp
        0429_39.cpp
        0429_40.cpp
        0429_41.cpp
        0429_42.cpp
        0429_43.cpp
        0429_44.cpp
        0429_45.cpp
        0429_46.cpp
        0429_47.cpp
        0429_48.cpp
        0429_49.cpp
        0501_1.cpp
        0501_2.cpp
        0501_3.cpp
        0501_4.cpp
        0501_5.cpp
        _.cpp
        0501_6.cpp
        0501_7.cpp
        0503_1.cpp
        0503_2.cpp
        0503_3.cpp
        0503_4.cpp
        0503_5.cpp
        0504_1.cpp
        0505_1.cpp
        0505_2.cpp
        0505_3.cpp
        0505_4.cpp
        0505_5.cpp
        0505_6.cpp
        0505_7.cpp
        0505_8.cpp
        0505_9.cpp
        0505_10.cpp
        0505_11.cpp
        0505_12.cpp
        0505_13.cpp
        0505_14.cpp
        0505_15.cpp
        0505_16.cpp
        0505_17.cpp
        0505_18.cpp
        0505_19.cpp
        0505_20.cpp
        0505_21.cpp
        0505_22.cpp
        0505_23.cpp
        0505_24.cpp
        0505_25.cpp
        0506_1.cpp
        0506_2.cpp
        0506_3.cpp
        0506_4.cpp
        0506_5.cpp
        0506_6.cpp
        0506_7.cpp
        0506_8.cpp
        0506_9.cpp
        0506_10.cpp
        0506_11.cpp
        0506_12.cpp
        0506_13.cpp
        0506_14.cpp
        0506_15.cpp
        0506_16.cpp
        0506_17.cpp
        0506_18.cpp
        0506_19.cpp
        0506_20.cpp
        0507_1.cpp
        0507_1.cpp
        0507_1.cpp
        0507_2.cpp
        0507_2.cpp
        0507_3.cpp
        0507_3.cpp
        0507_4.cpp
        0507_5.cpp
        0508_1.cpp
        0508_2.cpp
        0508_3.cpp
        0508_4.cpp
        0508_5.cpp
        0509_1.cpp
        0509_2.cpp
        0509_3.cpp
        0509_4.cpp
        0510_1.cpp
        0510_2.cpp
        0510_3.cpp
        0510_4.cpp
        0510_5.cpp
        0511_1.cpp
        0511_2.cpp
        0511_3.cpp
        0511_4.cpp
        0511_5.cpp
        0511_6.cpp
        0511_7.cpp
        0511_8.cpp
        0511_9.cpp
        0511_10.cpp
        0511_11.cpp
        0511_12.cpp
        0511_13.cpp
        0511_14.cpp
        0511_15.cpp
        0511_16.cpp
        0511_17.cpp
        0511_18.cpp
        0511_19.cpp
        0511_20.cpp
        0511_21.cpp
        0511_22.cpp
        0511_23.cpp
        0511_24.cpp
        0511_25.cpp
        0511_26.cpp
        0513_1.cpp
        0513_2.cpp
        0514_1.cpp
        0514_2.cpp
        0514_3.cpp
        0514_4.cpp
        0515_1.cpp
        0515_2.cpp
        0515_5.cpp
        0515_6.cpp
        0516_1.cpp
        0516_2.cpp
        0516_3.cpp
        0516_4.cpp
        0516_5.cpp
        0516_6.cpp
        0516_7.cpp
        0516_8.cpp
        0516_9.cpp
        0516_10.cpp
        0516_11.cpp
        0516_12.cpp
        1517_1.cpp
        0517_2.cpp
        0517_3.cpp
        0517_4.cpp
        0517_5.cpp
        0517_6.cpp
        0518_1.cpp
        0518_2.cpp
        0518_3.cpp
        0518_4.cpp
        0518_5.cpp
        0518_6.cpp
        0519_1.cpp
        0519_2.cpp
        0519_3.cpp
        0519_4.cpp
        0519_5.cpp
        0519_6.cpp
        0519_7.cpp
        0519_8.cpp
        0520_1.cpp
        0520_2.cpp
        0520_3.cpp
        0520_4.cpp
        0521_1.cpp
        0521_2.cpp
        0521_3.cpp
        0521_4.cpp
        0521_5.cpp
        0521_6.cpp
        0521_7.cpp
        0521_8.cpp
        0522_1.cpp
        0522_2.cpp
        0522_3.cpp
        0522_4.cpp
        0523_1.cpp
        0523_2.cpp
        0524_1.cpp
        0524_2.cpp
        0524_3.cpp
        0524_4.cpp
        0524_5.cpp
        0524_6.cpp
        0524_7.cpp
        0524_8.c
        0524_9.cpp
        0524_9.cpp
        0524_10.cpp
        0524_11.cpp
        0524_12.cpp
        0524_13.cpp
        0524_14.cpp
        0524_14.cpp
        0524_14.cpp
        0524_15.cpp
        0524_16.cpp
        0524_17.cpp
        0524_18.cpp
        0524_19.cpp
        0524_20.cpp
        0524_21.cpp
        0524_22.cpp
        0524_23.cpp
        0524_24.cpp
        0524_25.cpp
        0524_26.cpp
        0524_27.cpp
        0524_28.cpp
        0524_29.cpp
        0524_30.cpp
        0524_31.cpp
        0524_32.cpp
        0524_33.cpp
        0524_34.cpp
        0524_35.cpp
        0524_36.cpp
        0524_37.cpp
        0524_38.cpp
        0524_39.cpp
        0524_40.cpp
        0524_41.cpp
        0524_42.cpp
        0524_43.cpp
        0524_44.cpp
        0524_45.cpp
        0524_46.cpp
        0524_47.cpp
        0524_48.cpp
        0524_49.cpp
        0524_50.cpp
        0524_51.cpp
        0524_52.cpp
        0524_53.cpp
        0524_54.cpp
        0524_55.cpp
        0525_1.cpp
        0525_2.cpp
        0525_3.cpp
        0525_4.cpp
        0525_5.cpp
        0525_6.cpp
        0525_7.cpp
        0525_8.cpp
        0526_9.cpp
        0526_1.cpp
        0526_2.cpp
        0526_3.cpp
        0526_4.cpp
        0526_5.cpp
        0527_1.cpp
        0527_2.cpp
        0527_3.cpp
        0527_4.cpp
        0527_5.cpp
        0527_6.cpp
        0527_7.cpp
        0528_1.cpp
        0528_2.cpp
        0529_1.cpp
        0529_2.cpp
        0529_3.cpp
        0529_4.cpp
        0529_5.cpp
        0529_6.cpp
        0529_7.cpp
        0529_8.cpp
        0529_9.cpp
        0530_1.cpp
        0530_2.cpp
        0530_3.cpp
        0530_4.cpp
        0530_5.cpp
        0530_6.cpp
        0531_1.cpp
        0531_2.cpp
        0531_3.cpp
        0531_4.cpp
        0531_5.cpp
        0531_6.cpp
        0604_2.cpp
        0604_1.cpp
        0604_3.cpp
        0604_4.cpp
        0605_1.cpp
        0605_2.cpp
        0605_3.cpp
        0606_1.cpp
        0606_2.cpp
        0606_3.cpp
        0608_1.cpp
        0608_2.cpp
        0609_1.cpp
        0609_2.cpp
        0609_3.cpp
        0609_4.cpp
        0609_5.cpp
        0609_6.cpp
        0610_1.cpp
        0610_2.cpp
        0610_3.cpp
        0611_1.cpp
        0611_2.cpp
        0611_3.cpp
        0611_4.cpp
        0611_5.cpp
        0611_6.cpp
        0611_7.cpp
        0612_1.cpp
        0612_2.cpp
        0613_1.cpp
        0613_2.cpp
        0616_1.cpp
        0617_1.cpp
        0618_1.cpp
        0618_2.cpp
        0618_3.cpp
        0618_4.cpp
        0618_5.cpp
        0618_6.cpp
        0618_7.cpp
        0619_1.cpp
        0619_2.cpp
        0619_3.cpp
        0619_4.cpp
        0619_5.cpp
        0619_6.cpp
        0619_7.cpp
        0619_8.cpp
        0619_9.cpp
        0619_10.cpp
        0619_11.cpp
        0620_1.cpp
        0621_1.cpp
        0621_2.cpp
        0621_3.cpp
        0621_4.cpp
        0621_5.cpp
        0621_6.cpp
        0621_7.cpp
        0621_8.cpp
        0621_9.cpp
        0621_10.cpp
        0621_11.cpp
        0621_12.cpp
        0621_13.cpp
        0621_14.cpp
        0621_15.cpp
        0621_16.cpp
        0621_17.cpp
        0621_18.cpp
        0621_19.cpp
        0621_20.cpp
        0621_21.cpp
        0624_1.cpp
        0624_2.cpp
        0624_3.cpp
        0624_4.cpp
        0625_1.cpp
        0625_2.cpp
        0625_3.cpp
        0625_4.cpp
        0625_5.cpp
        0625_6.cpp
        0625_7.cpp
        0626_1.cpp
        0626_2.cpp
        0626_3.cpp
        0626_4.cpp
        0627_1.cpp
        0628_1.cpp
        0628_2.cpp
        0628_3.cpp
        0628_4.cpp
        0628_5.cpp
        0630_1.cpp
        0630_2.cpp
        0630_3.cpp
        0630_4.cpp
        0630_5.cpp
        0630_6.cpp
        0630_7.cpp
        0630_8.cpp
        0630_9.cpp
        0630_10.cpp
        0630_11.cpp
        0630_12.cpp
        0630_13.cpp
        0630_14.cpp
        0630_15.cpp
        0630_16.cpp
        0630_17.cpp
        0630_18.cpp
        0630_19.cpp
        0630_20.cpp
        0630_21.cpp
        0630_22.cpp
        0630_23.cpp
        0630_24.cpp
        0630_25.cpp
        0630_26.cpp
        0630_27.cpp
        0701_1.cpp
        0701_2.cpp
        0701_3.cpp
        0701_4.cpp
        0701_5.cpp
        0701_6.cpp
        0702_1.cpp
        0702_2.cpp
        0702_3.cpp
        0702_4.cpp
        0702_5.cpp
        0702_6.cpp
        0702_7.cpp
        0702_8.cpp
        0702_9.cpp
        0702_10.cpp
        0702_11.cpp
        0702_12.cpp
        0702_13.cpp
        0702_14.cpp
        0702_15.cpp
        0702_16.cpp
        0702_17.cpp
        0702_18.cpp
        0702_19.cpp
        0702_20.cpp
        0702_21.cpp
        0702_22.cpp
        0702_23.cpp
        0704_1.cpp
        0704_2.cpp
        0704_3.cpp
        0705_1.cpp
        0705_2.cpp
        0705_3.cpp
        0705_4.cpp
        0705_5.cpp
        0705_6.cpp
        0705_7.cpp
        0705_8.cpp
        0705_9.cpp
        0705_10.cpp
        0705_11.cpp
        0705_12.cpp
        0705_13.cpp
        0705_14.cpp
        0705_15.cpp
        0705_16.cpp
        0705_17.cpp
        0705_18.cpp
        0705_19.cpp
        0705_20.cpp
        0705_21.cpp
        0705_22.cpp
        0706_23.cpp
        0706_24.cpp
        0706_1.cpp
        0706_2.cpp
        0707_1.cpp
        0707_2.cpp
        0707_3.cpp
        0707_4.cpp
        0707_5.cpp
        0707_6.cpp
        0707_7.cpp
        0707_8.cpp
        0707_9.cpp
        0707_10.cpp
        0707_11.cpp
        0708_1.cpp
        0708_2.cpp
        0708_3.cpp
        0708_4.cpp
        0708_5.cpp
        0708_6.cpp
        0708_7.cpp
        0709_1.cpp
        0709_2.cpp
        0709_3.cpp
        0709_4.cpp
        0709_5.cpp
        0709_6.cpp
        0709_7.cpp
        0709_8.cpp
        0709_9.cpp
        0709_10.cpp
        0709_11.cpp
        0709_12.cpp
        0709_13.cpp
        0709_14.cpp
        0710_1.cpp
        0710_2.cpp
        0710_3.cpp
        0710_4.cpp
        0710_5.cpp
        0710_6.cpp
        0710_7.cpp
        0710_8.cpp
        0710_9.cpp
        0710_10.cpp
        0711_1.cpp
        0711_2.cpp
        0711_3.cpp
        0711_4.cpp
        0711_5.cpp
        0711_6.cpp
        0711_7.cpp
        0711_8.cpp
        0711_9.cpp
        0711_10.cpp
        0711_11.cpp
        0711_12.cpp
        0711_13.cpp
        0711_14.cpp
        0711_15.cpp
        0711_16.cpp
        0711_17.cpp
        0711_18.cpp
        0711_19.cpp
        0711_20.cpp
        0711_21.cpp
        0711_22.cpp
        0712_1.cpp
        0712_2.cpp
        0712_3.cpp
        0712_4.cpp
        0712_5.cpp
        0712_6.cpp
        0712_7.cpp
        0712_8.cpp
        0712_9.cpp
        0713_1.cpp
        0713_2.cpp
        0713_3.cpp
        0713_4.cpp
        0713_5.cpp
        0713_6.cpp
        0713_7.cpp
        0714_1.cpp
        0714_2.cpp
        0714_3.cpp
        0714_4.cpp
        0714_5.cpp
        0714_6.cpp
        0714_7.cpp
        0714_8.cpp
        0714_9.cpp
        0714_10.cpp
        0715_1.cpp
        0715_2.cpp
        0715_3.cpp
        0715_4.cpp
        0715_5.cpp
        0715_6.cpp
        0715_7.cpp
        0715_8.cpp
        0715_9.cpp
        0715_10.cpp
        0715_11.cpp
        0716_1.cpp
        0716_2.cpp
        0716_3.cpp
        0716_4.cpp
        0716_5.cpp
        0716_6.cpp
        0716_7.cpp
        0716_8.cpp
        0716_9.cpp
        0718_1.cpp
        0718_2.cpp
        0718_3.cpp
        0718_4.cpp
        0722_1.cpp
        0722_2.cpp
        0722_3.cpp
        0722_4.cpp
        0722_5.cpp
        0722_6.cpp
        0722_7.cpp
        0722_8.cpp
        0722_9.cpp
        0723_1.cpp
        0723_2.cpp
        0723_3.cpp
        0723_4.cpp
        0723_5.cpp
        0723_6.cpp
        0724_1.cpp
        0724_2.cpp
        0725_1.cpp
        0725_2.cpp
        0725_3.cpp
        0725_4.cpp
        0725_5.cpp
        0725_6.cpp
        0725_7.cpp
        0725_8.cpp
        0725_9.cpp
        0725_10.cpp
        0725_11.cpp
        0725_12.cpp
        0725_13.cpp
        0725_14.cpp
        0725_15.cpp
        0725_16.cpp
        0725_17.cpp
        0725_18.cpp
        0725_19.cpp
        0725_20.cpp
        0725_21.cpp
        0725_22.cpp
        0725_23.cpp
        0725_24.cpp
        0725_25.cpp
        0725_26.cpp
        0725_27.cpp
        0725_28.cpp
        0725_29.cpp
        0725_30.cpp
        0725_31.cpp
        0725_32.cpp
        0725_33.cpp
        0725_34.cpp
        0726_1.cpp
        0726_2.cpp
        0726_3.cpp
        0726_4.cpp
        0726_5.cpp
        0726_6.cpp
        0726_7.cpp
        0726_8.cpp
        0726_9.cpp
        0726_10.cpp
        0726_11.cpp
        0726_12.cpp
        0726_13.cpp
        0726_14.cpp
        0726_15.cpp
        0726_16.cpp
        0726_17.cpp
        0726_18.cpp
        0726_19.cpp
        0726_20.cpp
        0726_21.cpp
        0726_22.cpp
        0726_23.cpp
        0726_24.cpp
        0726_25.cpp
        0726_26.cpp
        0726_27.cpp
        0726_28.cpp
        0726_29.cpp
        0726_30.cpp
        0726_31.cpp
        0726_32.cpp
        0726_33.cpp
        0726_34.cpp
        0726_35.cpp
        0726_36.cpp
        0726_37.cpp
        0726_38.cpp
        0726_39.cpp
        0726_40.cpp
        0726_41.cpp
        0726_42.cpp
        0726_43.cpp
        0726_44.cpp
        0727_1.cpp
        0727_2.cpp
        0727_3.cpp
        0727_4.cpp
        0727_5.cpp
        0727_6.cpp
        0727_7.cpp
        0727_8.cpp
        0727_9.cpp
        0727_10.cpp
        0727_11.cpp
        0727_12.cpp
        0727_13.cpp
        0727_14.cpp
        0728_1.cpp
        0728_2.cpp
        0729_1.cpp
        0729_2.cpp
        0729_3.cpp
        0730_1.cpp
        0730_2.cpp
        0730_3.cpp
        0730_4.cpp
        0730_5.cpp
        0731_1.cpp
        0731_2.cpp
        0731_3.cpp
        0731_4.cpp
        0731_5.cpp
        0731_6.cpp
        0731_7.cpp
        0731_8.cpp
        0731_9.cpp
        0731_10.cpp
        0731_11.cpp
        0731_12.cpp
        0731_13.cpp
        0731_14.cpp
        0801_1.cpp
        0801_2.cpp
        0801_3.cpp
        0801_4.cpp
        0801_5.cpp
        0801_6.cpp
        0801_7.cpp
        0801_8.cpp
        0801_9.cpp
        0801_10.cpp
        0801_11.cpp
        0801_12.cpp
        0801_13.cpp
        0801_14.cpp
        0801_15.cpp
        0801_16.cpp
        0801_17.cpp
        0801_18.cpp
        0801_19.cpp
        0802_1.cpp
        0802_2.cpp
        0802_3.cpp
        0802_4.cpp
        0802_5.cpp
        0802_6.cpp
        0802_7.cpp
        0802_8.cpp
        0802_9.cpp
        0802_10.cpp
        0802_11.cpp
        0803_1.cpp
        0803_2.cpp
        0803_3.cpp
        0803_4.cpp
        0804_1.cpp
        0804_2.cpp
        0804_3.cpp
        0804_4.cpp
        0804_5.cpp
        0804_6.cpp
        0804_7.cpp
        0804_8.cpp
        0805_1.cpp
        0805_2.cpp
        0805_3.cpp
        0805_4.cpp
        0805_5.cpp
        0805_6.cpp
        0805_7.cpp
        0805_8.cpp
        0805_9.cpp
        0805_10.cpp
        0805_11.cpp
        0805_12.cpp
        0805_13.cpp
        0805_14.cpp
        0805_15.cpp
        0805_16.cpp
        0806_1.cpp
        0806_2.cpp
        0806_3.cpp
        0807_1.cpp
        0807_1.cpp
        0809_1.cpp
        0810_1.cpp
        0810_2.cpp
        0810_3.cpp
        0812_1.cpp
        0813_1.cpp
        0814_1.cpp
        0814_2.cpp
        0815_1.cpp
        0816_1.cpp
        0816_2.cpp
        0817_1.cpp
        0817_2.cpp
        0817_3.cpp
        0817_4.cpp
        0817_5.cpp
        0817_6.cpp
        0818_1.cpp
        0818_2.cpp
        0819_1.cpp
        0820_1.cpp
        0820_2.cpp
        0820_3.cpp
        0820_4.cpp
        0820_5.cpp
        0820_6.cpp
        0821_1.cpp
        0821_2.cpp
        0821_3.cpp
        0822_1.cpp
        0822_2.cpp
        0822_3.cpp
        0822_4.cpp
        0823_1.cpp
        0823_2.cpp
        0824_1.cpp
        0824_2.cpp
        0824_3.cpp
        0825_1.cpp
        0825_2.cpp
        0826_1.cpp
        0827_1.cpp
        0827_2.cpp
        0827_3.cpp
        0828_1.cpp
        0830_1.cpp
        0830_2.cpp
        0831_1.cpp
        0901_1.cpp
        0901_2.cpp
        0902_1.cpp
        0903_1.cpp
        0903_2.cpp
        0904_1.cpp
        0904_2.cpp
        0906_1.cpp
        0906_2.cpp
        0908_1.cpp
        0908_2.cpp
        0908_3.cpp
        0911_1.cpp
        0911_3.cpp
        0913_1.cpp
        0914_1.cpp
        0915_1.cpp
        0915_1.cpp
        0915_2.h
        0915_2.cpp
        0915_3.cpp
        0915_4.cpp
        0916_1.cpp
        0916_2.cpp
        0917_1.cpp
        0919_1.cpp
        0920_1.cpp
        0920_2.cpp
        0920_3.cpp
        0920_4.cpp
        0921_1.cpp
        0921_2.cpp
        0922_1.cpp
        0923_1.cpp
        0923_2.cpp
        0924_1.cpp
        0925_1.cpp
        0926_1.cpp
        0927_1.cpp
        0927_2.cpp
        0927_3.cpp
        0929_1.cpp
        0930_1.cpp
        1001_1.cpp
        1002_1.cpp
        1002_2.cpp
        1003_1.cpp
        1006_1.cpp
        1007_1.cpp
        1009_1.cpp
        1010_1.cpp
        1011_1.cpp
        1012_1.cpp
        1013_1.cpp
        1014_1.cpp
        1015_1.cpp
        1016_1.cpp
        1017_1.cpp
        1018_1.cpp
        1018_2.cpp
        1018_3.cpp
        1018_4.cpp
        1018_5.cpp
        1018_6.cpp
        1018_7.cpp
        1018_8.cpp
        1018_9.cpp
        1018_10.cpp
        1018_11.cpp
        1018_12.cpp
        1018_13.cpp
        1018_14.cpp
        1018_15.cpp
        1018_16.cpp
        1018_17.cpp
        1018_18.cpp
        1018_19.cpp
        1019_1.cpp
        1019_2.cpp
        1019_3.cpp
        1019_4.cpp
        1019_5.cpp
        1019_6.cpp
        1019_7.cpp
        1019_8.cpp
        1019_9.cpp
        1019_10.cpp
        1019_11.cpp
        1019_12.cpp
        1020_1.cpp
        1020_2.cpp
        1021_1.cpp
        1022_1.cpp
        1022_2.cpp
        1022_3.cpp
        1022_4.cpp
        1023_1.cpp
        1023_2.cpp
        1023_3.cpp
        1023_4.cpp
        1024_1.cpp
        1025_1.cpp
        1025_2.cpp
        1025_3.cpp
        1026_1.cpp
        1026_2.cpp
        1026_3.cpp
        1026_4.cpp
        1026_5.cpp
        1026_6.cpp
        1026_7.cpp
        1026_8.cpp
        1026_9.cpp
        1026_10.cpp
        1026_11.cpp
        1027_1.cpp
        1027_2.cpp
        1027_3.cpp
        1027_4.cpp
        1027_5.cpp
        1027_6.cpp
        1027_7.cpp
        1027_8.cpp
        1027_9.cpp
        1027_10.cpp
        1027_11.cpp
        1027_12.cpp
        1027_13.cpp
        1027_14.cpp
        1027_15.cpp
        1027_16.cpp
        1027_17.cpp
        1028.cpp
        1028_1.cpp
        1028_2.cpp
        1028_3.cpp
        1028_4.cpp
        1028_5.cpp
        1028_6.cpp
        1028_7.cpp
        1029_1.cpp
        1029_2.cpp
        1029_3.cpp
        1029_4.cpp
        1029_5.cpp
        1029_6.cpp
        1029_7.cpp
        1029_8.cpp
        1029_9.cpp
        1029_10.cpp
        1029_11.cpp
        1030_1.cpp
        1031_1.cpp
        1101_1.cpp
        1101_2.cpp
        1102_1.cpp
        1102_2.cpp
        1102_3.cpp
        1102_4.cpp
        1102_5.cpp
        1102_6.cpp
        1102_7.cpp
        1103_1.cpp
        1103_2.cpp
        1103_3.cpp
        1103_4.cpp
        1103_5.cpp
        1103_6.cpp
        1103_7.cpp
        1103_8.cpp
        1103_9.cpp
        1103_10.cpp
        1103_11.cpp
        1103_12.cpp
        1104_1.cpp
        1105_1.cpp
        1106_1.cpp
        1106_2.cpp
        1107_1.cpp
        1107_2.cpp
        1107_3.cpp
        1108_1.cpp
        1108_2.cpp
        1108_3.cpp
        1109_1.cpp
        1109_2.cpp
        1109_3.cpp
        1109_4.cpp
        1109_5.cpp
        1109_6.cpp
        1111_1.cpp
        1111_2.cpp
        1111_3.cpp
        1112_1.cpp
        1112_2.cpp
        1114_1.cpp
        1114_2.cpp
        1114_3.cpp
        1115_1.cpp
        1115_2.cpp
        1116_1.cpp
        1116_2.cpp
        1116_3.cpp
        1116_4.cpp
        1117_1.cpp
        1117_2.cpp
        1117_3.cpp)
